<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerStegfsk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerStegfsk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerStegfsk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerStegfsk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerStegfsk\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Stegfsk',
    'container.build_id' => 'ad4149f0',
    'container.build_time' => 1543082854,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerStegfsk');
