<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK0qrj6z\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK0qrj6z/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerK0qrj6z.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerK0qrj6z\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerK0qrj6z\appProdProjectContainer(array(
    'container.build_hash' => 'K0qrj6z',
    'container.build_id' => '4f57ce0b',
    'container.build_time' => 1543083018,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerK0qrj6z');
